# ("amd64" -> "x86_64", "386" -> "i386", arm -> "armv7").
class Codg < Formula
  desc "Terminal-based AI coding assistant for developers"
  homepage "https://github.com/vcaesar/codg"
  version "2.0.1"
  license "EULA"

  on_macos do
     on_arm do
      url "https://github.com/vcaesar/codg/releases/download/v#{version}/codg_#{version}_Darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_DARWIN_ARM64"
    end
    
    on_intel do
      url "https://github.com/vcaesar/codg/releases/download/v#{version}/codg_#{version}_Darwin_x86_64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vcaesar/codg/releases/download/v#{version}/codg_#{version}_Linux_x86_64.tar.gz"
      sha256 "REPLACE_WITH_SHA256_LINUX_AMD64"
    end

    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vcaesar/codg/releases/download/v#{version}/codg_#{version}_Linux_arm64.tar.gz"
        sha256 "REPLACE_WITH_SHA256_LINUX_ARM64"
      else
        url "https://github.com/vcaesar/codg/releases/download/v#{version}/codg_#{version}_Linux_armv7.tar.gz"
        sha256 "REPLACE_WITH_SHA256_LINUX_ARMV7"
      end
    end
  end

  def install
    bin.install "codg"

    # Shell completions (generated by `codg completion <shell>` at release).
    bash_completion.install "completions/codg.bash" => "codg"
    zsh_completion.install  "completions/codg.zsh"  => "_codg"
    fish_completion.install "completions/codg.fish"

    # Man page.
    man1.install "manpages/codg.1.gz"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codg --version")
  end
end